// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: input_ports.proto
// Protobuf C++ Version: 6.30.1

#ifndef input_5fports_2eproto_2epb_2eh
#define input_5fports_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_input_5fports_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_input_5fports_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_input_5fports_2eproto;
}  // extern "C"
namespace pmx {
namespace grpc {
class ClearInputPortRequest;
struct ClearInputPortRequestDefaultTypeInternal;
extern ClearInputPortRequestDefaultTypeInternal _ClearInputPortRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ClearInputPortRequest_class_data_;
class InputPortSetup;
struct InputPortSetupDefaultTypeInternal;
extern InputPortSetupDefaultTypeInternal _InputPortSetup_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull InputPortSetup_class_data_;
class ListInputPortSetupResponse;
struct ListInputPortSetupResponseDefaultTypeInternal;
extern ListInputPortSetupResponseDefaultTypeInternal _ListInputPortSetupResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ListInputPortSetupResponse_class_data_;
class SetupInputPortRequest;
struct SetupInputPortRequestDefaultTypeInternal;
extern SetupInputPortRequestDefaultTypeInternal _SetupInputPortRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SetupInputPortRequest_class_data_;
}  // namespace grpc
}  // namespace pmx
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace pmx {
namespace grpc {

// ===================================================================


// -------------------------------------------------------------------

class SetupInputPortRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:pmx.grpc.SetupInputPortRequest) */ {
 public:
  inline SetupInputPortRequest() : SetupInputPortRequest(nullptr) {}
  ~SetupInputPortRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SetupInputPortRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SetupInputPortRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SetupInputPortRequest(::google::protobuf::internal::ConstantInitialized);

  inline SetupInputPortRequest(const SetupInputPortRequest& from) : SetupInputPortRequest(nullptr, from) {}
  inline SetupInputPortRequest(SetupInputPortRequest&& from) noexcept
      : SetupInputPortRequest(nullptr, std::move(from)) {}
  inline SetupInputPortRequest& operator=(const SetupInputPortRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SetupInputPortRequest& operator=(SetupInputPortRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SetupInputPortRequest& default_instance() {
    return *reinterpret_cast<const SetupInputPortRequest*>(
        &_SetupInputPortRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SetupInputPortRequest& a, SetupInputPortRequest& b) { a.Swap(&b); }
  inline void Swap(SetupInputPortRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SetupInputPortRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SetupInputPortRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SetupInputPortRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SetupInputPortRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SetupInputPortRequest& from) { SetupInputPortRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SetupInputPortRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "pmx.grpc.SetupInputPortRequest"; }

 protected:
  explicit SetupInputPortRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SetupInputPortRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SetupInputPortRequest& from);
  SetupInputPortRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SetupInputPortRequest&& from) noexcept
      : SetupInputPortRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPortFieldNumber = 2,
    kChannelIdFieldNumber = 1,
    kGroupChannelIdFieldNumber = 3,
  };
  // optional string port = 2;
  bool has_port() const;
  void clear_port() ;
  const std::string& port() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_port(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_port();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_port();
  void set_allocated_port(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_port() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_port(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_port();

  public:
  // uint32 channel_id = 1;
  void clear_channel_id() ;
  ::uint32_t channel_id() const;
  void set_channel_id(::uint32_t value);

  private:
  ::uint32_t _internal_channel_id() const;
  void _internal_set_channel_id(::uint32_t value);

  public:
  // optional uint32 group_channel_id = 3;
  bool has_group_channel_id() const;
  void clear_group_channel_id() ;
  ::uint32_t group_channel_id() const;
  void set_group_channel_id(::uint32_t value);

  private:
  ::uint32_t _internal_group_channel_id() const;
  void _internal_set_group_channel_id(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:pmx.grpc.SetupInputPortRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 43,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SetupInputPortRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr port_;
    ::uint32_t channel_id_;
    ::uint32_t group_channel_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_input_5fports_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SetupInputPortRequest_class_data_;
// -------------------------------------------------------------------

class InputPortSetup final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:pmx.grpc.InputPortSetup) */ {
 public:
  inline InputPortSetup() : InputPortSetup(nullptr) {}
  ~InputPortSetup() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(InputPortSetup* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(InputPortSetup));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR InputPortSetup(::google::protobuf::internal::ConstantInitialized);

  inline InputPortSetup(const InputPortSetup& from) : InputPortSetup(nullptr, from) {}
  inline InputPortSetup(InputPortSetup&& from) noexcept
      : InputPortSetup(nullptr, std::move(from)) {}
  inline InputPortSetup& operator=(const InputPortSetup& from) {
    CopyFrom(from);
    return *this;
  }
  inline InputPortSetup& operator=(InputPortSetup&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InputPortSetup& default_instance() {
    return *reinterpret_cast<const InputPortSetup*>(
        &_InputPortSetup_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(InputPortSetup& a, InputPortSetup& b) { a.Swap(&b); }
  inline void Swap(InputPortSetup* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InputPortSetup* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InputPortSetup* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<InputPortSetup>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const InputPortSetup& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const InputPortSetup& from) { InputPortSetup::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(InputPortSetup* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "pmx.grpc.InputPortSetup"; }

 protected:
  explicit InputPortSetup(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  InputPortSetup(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const InputPortSetup& from);
  InputPortSetup(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, InputPortSetup&& from) noexcept
      : InputPortSetup(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPortFieldNumber = 2,
    kChannelIdFieldNumber = 1,
    kGroupChannelIdFieldNumber = 3,
  };
  // optional string port = 2;
  bool has_port() const;
  void clear_port() ;
  const std::string& port() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_port(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_port();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_port();
  void set_allocated_port(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_port() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_port(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_port();

  public:
  // uint32 channel_id = 1;
  void clear_channel_id() ;
  ::uint32_t channel_id() const;
  void set_channel_id(::uint32_t value);

  private:
  ::uint32_t _internal_channel_id() const;
  void _internal_set_channel_id(::uint32_t value);

  public:
  // optional uint32 group_channel_id = 3;
  bool has_group_channel_id() const;
  void clear_group_channel_id() ;
  ::uint32_t group_channel_id() const;
  void set_group_channel_id(::uint32_t value);

  private:
  ::uint32_t _internal_group_channel_id() const;
  void _internal_set_group_channel_id(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:pmx.grpc.InputPortSetup)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 36,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const InputPortSetup& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr port_;
    ::uint32_t channel_id_;
    ::uint32_t group_channel_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_input_5fports_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull InputPortSetup_class_data_;
// -------------------------------------------------------------------

class ClearInputPortRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:pmx.grpc.ClearInputPortRequest) */ {
 public:
  inline ClearInputPortRequest() : ClearInputPortRequest(nullptr) {}
  ~ClearInputPortRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ClearInputPortRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ClearInputPortRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ClearInputPortRequest(::google::protobuf::internal::ConstantInitialized);

  inline ClearInputPortRequest(const ClearInputPortRequest& from) : ClearInputPortRequest(nullptr, from) {}
  inline ClearInputPortRequest(ClearInputPortRequest&& from) noexcept
      : ClearInputPortRequest(nullptr, std::move(from)) {}
  inline ClearInputPortRequest& operator=(const ClearInputPortRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClearInputPortRequest& operator=(ClearInputPortRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClearInputPortRequest& default_instance() {
    return *reinterpret_cast<const ClearInputPortRequest*>(
        &_ClearInputPortRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ClearInputPortRequest& a, ClearInputPortRequest& b) { a.Swap(&b); }
  inline void Swap(ClearInputPortRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClearInputPortRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClearInputPortRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ClearInputPortRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ClearInputPortRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ClearInputPortRequest& from) { ClearInputPortRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ClearInputPortRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "pmx.grpc.ClearInputPortRequest"; }

 protected:
  explicit ClearInputPortRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ClearInputPortRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ClearInputPortRequest& from);
  ClearInputPortRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ClearInputPortRequest&& from) noexcept
      : ClearInputPortRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kChannelIdFieldNumber = 1,
  };
  // uint32 channel_id = 1;
  void clear_channel_id() ;
  ::uint32_t channel_id() const;
  void set_channel_id(::uint32_t value);

  private:
  ::uint32_t _internal_channel_id() const;
  void _internal_set_channel_id(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:pmx.grpc.ClearInputPortRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ClearInputPortRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t channel_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_input_5fports_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ClearInputPortRequest_class_data_;
// -------------------------------------------------------------------

class ListInputPortSetupResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:pmx.grpc.ListInputPortSetupResponse) */ {
 public:
  inline ListInputPortSetupResponse() : ListInputPortSetupResponse(nullptr) {}
  ~ListInputPortSetupResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ListInputPortSetupResponse* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ListInputPortSetupResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ListInputPortSetupResponse(::google::protobuf::internal::ConstantInitialized);

  inline ListInputPortSetupResponse(const ListInputPortSetupResponse& from) : ListInputPortSetupResponse(nullptr, from) {}
  inline ListInputPortSetupResponse(ListInputPortSetupResponse&& from) noexcept
      : ListInputPortSetupResponse(nullptr, std::move(from)) {}
  inline ListInputPortSetupResponse& operator=(const ListInputPortSetupResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ListInputPortSetupResponse& operator=(ListInputPortSetupResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ListInputPortSetupResponse& default_instance() {
    return *reinterpret_cast<const ListInputPortSetupResponse*>(
        &_ListInputPortSetupResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(ListInputPortSetupResponse& a, ListInputPortSetupResponse& b) { a.Swap(&b); }
  inline void Swap(ListInputPortSetupResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ListInputPortSetupResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ListInputPortSetupResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ListInputPortSetupResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ListInputPortSetupResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ListInputPortSetupResponse& from) { ListInputPortSetupResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ListInputPortSetupResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "pmx.grpc.ListInputPortSetupResponse"; }

 protected:
  explicit ListInputPortSetupResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ListInputPortSetupResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ListInputPortSetupResponse& from);
  ListInputPortSetupResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ListInputPortSetupResponse&& from) noexcept
      : ListInputPortSetupResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSetupsFieldNumber = 1,
  };
  // repeated .pmx.grpc.InputPortSetup setups = 1;
  int setups_size() const;
  private:
  int _internal_setups_size() const;

  public:
  void clear_setups() ;
  ::pmx::grpc::InputPortSetup* PROTOBUF_NONNULL mutable_setups(int index);
  ::google::protobuf::RepeatedPtrField<::pmx::grpc::InputPortSetup>* PROTOBUF_NONNULL mutable_setups();

  private:
  const ::google::protobuf::RepeatedPtrField<::pmx::grpc::InputPortSetup>& _internal_setups() const;
  ::google::protobuf::RepeatedPtrField<::pmx::grpc::InputPortSetup>* PROTOBUF_NONNULL _internal_mutable_setups();
  public:
  const ::pmx::grpc::InputPortSetup& setups(int index) const;
  ::pmx::grpc::InputPortSetup* PROTOBUF_NONNULL add_setups();
  const ::google::protobuf::RepeatedPtrField<::pmx::grpc::InputPortSetup>& setups() const;
  // @@protoc_insertion_point(class_scope:pmx.grpc.ListInputPortSetupResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ListInputPortSetupResponse& from_msg);
    ::google::protobuf::RepeatedPtrField< ::pmx::grpc::InputPortSetup > setups_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_input_5fports_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ListInputPortSetupResponse_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SetupInputPortRequest

// uint32 channel_id = 1;
inline void SetupInputPortRequest::clear_channel_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.channel_id_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::uint32_t SetupInputPortRequest::channel_id() const {
  // @@protoc_insertion_point(field_get:pmx.grpc.SetupInputPortRequest.channel_id)
  return _internal_channel_id();
}
inline void SetupInputPortRequest::set_channel_id(::uint32_t value) {
  _internal_set_channel_id(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:pmx.grpc.SetupInputPortRequest.channel_id)
}
inline ::uint32_t SetupInputPortRequest::_internal_channel_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.channel_id_;
}
inline void SetupInputPortRequest::_internal_set_channel_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.channel_id_ = value;
}

// optional string port = 2;
inline bool SetupInputPortRequest::has_port() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void SetupInputPortRequest::clear_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& SetupInputPortRequest::port() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:pmx.grpc.SetupInputPortRequest.port)
  return _internal_port();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SetupInputPortRequest::set_port(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.port_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:pmx.grpc.SetupInputPortRequest.port)
}
inline std::string* PROTOBUF_NONNULL SetupInputPortRequest::mutable_port()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_port();
  // @@protoc_insertion_point(field_mutable:pmx.grpc.SetupInputPortRequest.port)
  return _s;
}
inline const std::string& SetupInputPortRequest::_internal_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.port_.Get();
}
inline void SetupInputPortRequest::_internal_set_port(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.port_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL SetupInputPortRequest::_internal_mutable_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.port_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE SetupInputPortRequest::release_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:pmx.grpc.SetupInputPortRequest.port)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.port_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.port_.Set("", GetArena());
  }
  return released;
}
inline void SetupInputPortRequest::set_allocated_port(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.port_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.port_.IsDefault()) {
    _impl_.port_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:pmx.grpc.SetupInputPortRequest.port)
}

// optional uint32 group_channel_id = 3;
inline bool SetupInputPortRequest::has_group_channel_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void SetupInputPortRequest::clear_group_channel_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.group_channel_id_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::uint32_t SetupInputPortRequest::group_channel_id() const {
  // @@protoc_insertion_point(field_get:pmx.grpc.SetupInputPortRequest.group_channel_id)
  return _internal_group_channel_id();
}
inline void SetupInputPortRequest::set_group_channel_id(::uint32_t value) {
  _internal_set_group_channel_id(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:pmx.grpc.SetupInputPortRequest.group_channel_id)
}
inline ::uint32_t SetupInputPortRequest::_internal_group_channel_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.group_channel_id_;
}
inline void SetupInputPortRequest::_internal_set_group_channel_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.group_channel_id_ = value;
}

// -------------------------------------------------------------------

// ClearInputPortRequest

// uint32 channel_id = 1;
inline void ClearInputPortRequest::clear_channel_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.channel_id_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint32_t ClearInputPortRequest::channel_id() const {
  // @@protoc_insertion_point(field_get:pmx.grpc.ClearInputPortRequest.channel_id)
  return _internal_channel_id();
}
inline void ClearInputPortRequest::set_channel_id(::uint32_t value) {
  _internal_set_channel_id(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:pmx.grpc.ClearInputPortRequest.channel_id)
}
inline ::uint32_t ClearInputPortRequest::_internal_channel_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.channel_id_;
}
inline void ClearInputPortRequest::_internal_set_channel_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.channel_id_ = value;
}

// -------------------------------------------------------------------

// InputPortSetup

// uint32 channel_id = 1;
inline void InputPortSetup::clear_channel_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.channel_id_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::uint32_t InputPortSetup::channel_id() const {
  // @@protoc_insertion_point(field_get:pmx.grpc.InputPortSetup.channel_id)
  return _internal_channel_id();
}
inline void InputPortSetup::set_channel_id(::uint32_t value) {
  _internal_set_channel_id(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:pmx.grpc.InputPortSetup.channel_id)
}
inline ::uint32_t InputPortSetup::_internal_channel_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.channel_id_;
}
inline void InputPortSetup::_internal_set_channel_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.channel_id_ = value;
}

// optional string port = 2;
inline bool InputPortSetup::has_port() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void InputPortSetup::clear_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& InputPortSetup::port() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:pmx.grpc.InputPortSetup.port)
  return _internal_port();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void InputPortSetup::set_port(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.port_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:pmx.grpc.InputPortSetup.port)
}
inline std::string* PROTOBUF_NONNULL InputPortSetup::mutable_port()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_port();
  // @@protoc_insertion_point(field_mutable:pmx.grpc.InputPortSetup.port)
  return _s;
}
inline const std::string& InputPortSetup::_internal_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.port_.Get();
}
inline void InputPortSetup::_internal_set_port(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.port_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL InputPortSetup::_internal_mutable_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.port_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE InputPortSetup::release_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:pmx.grpc.InputPortSetup.port)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.port_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.port_.Set("", GetArena());
  }
  return released;
}
inline void InputPortSetup::set_allocated_port(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.port_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.port_.IsDefault()) {
    _impl_.port_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:pmx.grpc.InputPortSetup.port)
}

// optional uint32 group_channel_id = 3;
inline bool InputPortSetup::has_group_channel_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void InputPortSetup::clear_group_channel_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.group_channel_id_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::uint32_t InputPortSetup::group_channel_id() const {
  // @@protoc_insertion_point(field_get:pmx.grpc.InputPortSetup.group_channel_id)
  return _internal_group_channel_id();
}
inline void InputPortSetup::set_group_channel_id(::uint32_t value) {
  _internal_set_group_channel_id(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:pmx.grpc.InputPortSetup.group_channel_id)
}
inline ::uint32_t InputPortSetup::_internal_group_channel_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.group_channel_id_;
}
inline void InputPortSetup::_internal_set_group_channel_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.group_channel_id_ = value;
}

// -------------------------------------------------------------------

// ListInputPortSetupResponse

// repeated .pmx.grpc.InputPortSetup setups = 1;
inline int ListInputPortSetupResponse::_internal_setups_size() const {
  return _internal_setups().size();
}
inline int ListInputPortSetupResponse::setups_size() const {
  return _internal_setups_size();
}
inline void ListInputPortSetupResponse::clear_setups() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.setups_.Clear();
}
inline ::pmx::grpc::InputPortSetup* PROTOBUF_NONNULL ListInputPortSetupResponse::mutable_setups(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:pmx.grpc.ListInputPortSetupResponse.setups)
  return _internal_mutable_setups()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::pmx::grpc::InputPortSetup>* PROTOBUF_NONNULL ListInputPortSetupResponse::mutable_setups()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:pmx.grpc.ListInputPortSetupResponse.setups)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_setups();
}
inline const ::pmx::grpc::InputPortSetup& ListInputPortSetupResponse::setups(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:pmx.grpc.ListInputPortSetupResponse.setups)
  return _internal_setups().Get(index);
}
inline ::pmx::grpc::InputPortSetup* PROTOBUF_NONNULL ListInputPortSetupResponse::add_setups()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::pmx::grpc::InputPortSetup* _add = _internal_mutable_setups()->Add();
  // @@protoc_insertion_point(field_add:pmx.grpc.ListInputPortSetupResponse.setups)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::pmx::grpc::InputPortSetup>& ListInputPortSetupResponse::setups() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:pmx.grpc.ListInputPortSetupResponse.setups)
  return _internal_setups();
}
inline const ::google::protobuf::RepeatedPtrField<::pmx::grpc::InputPortSetup>&
ListInputPortSetupResponse::_internal_setups() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.setups_;
}
inline ::google::protobuf::RepeatedPtrField<::pmx::grpc::InputPortSetup>* PROTOBUF_NONNULL
ListInputPortSetupResponse::_internal_mutable_setups() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.setups_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace grpc
}  // namespace pmx


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // input_5fports_2eproto_2epb_2eh
