// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mono_port.proto
// Protobuf C++ Version: 6.30.2

#include "mono_port.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace pmx {
namespace grpc {

inline constexpr MonoPort::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        left_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR MonoPort::MonoPort(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(MonoPort_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MonoPortDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MonoPortDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MonoPortDefaultTypeInternal() {}
  union {
    MonoPort _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MonoPortDefaultTypeInternal _MonoPort_default_instance_;
}  // namespace grpc
}  // namespace pmx
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_mono_5fport_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_mono_5fport_2eproto = nullptr;
const ::uint32_t
    TableStruct_mono_5fport_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::pmx::grpc::MonoPort, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::pmx::grpc::MonoPort, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::pmx::grpc::MonoPort, _impl_.left_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::pmx::grpc::MonoPort)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::pmx::grpc::_MonoPort_default_instance_._instance,
};
const char descriptor_table_protodef_mono_5fport_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017mono_port.proto\022\010pmx.grpc\"\030\n\010MonoPort\022"
    "\014\n\004left\030\001 \001(\tb\006proto3"
};
static ::absl::once_flag descriptor_table_mono_5fport_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_mono_5fport_2eproto = {
    false,
    false,
    61,
    descriptor_table_protodef_mono_5fport_2eproto,
    "mono_port.proto",
    &descriptor_table_mono_5fport_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_mono_5fport_2eproto::offsets,
    file_level_enum_descriptors_mono_5fport_2eproto,
    file_level_service_descriptors_mono_5fport_2eproto,
};
namespace pmx {
namespace grpc {
// ===================================================================

class MonoPort::_Internal {
 public:
  using HasBits =
      decltype(std::declval<MonoPort>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MonoPort, _impl_._has_bits_);
};

MonoPort::MonoPort(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MonoPort_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:pmx.grpc.MonoPort)
}
PROTOBUF_NDEBUG_INLINE MonoPort::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::pmx::grpc::MonoPort& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        left_(arena, from.left_) {}

MonoPort::MonoPort(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const MonoPort& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MonoPort_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MonoPort* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:pmx.grpc.MonoPort)
}
PROTOBUF_NDEBUG_INLINE MonoPort::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        left_(arena) {}

inline void MonoPort::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
MonoPort::~MonoPort() {
  // @@protoc_insertion_point(destructor:pmx.grpc.MonoPort)
  SharedDtor(*this);
}
inline void MonoPort::SharedDtor(MessageLite& self) {
  MonoPort& this_ = static_cast<MonoPort&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.left_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL MonoPort::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) MonoPort(arena);
}
constexpr auto MonoPort::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(MonoPort),
                                            alignof(MonoPort));
}
constexpr auto MonoPort::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MonoPort_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &MonoPort::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MonoPort>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MonoPort::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MonoPort>(), &MonoPort::ByteSizeLong,
              &MonoPort::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MonoPort, _impl_._cached_size_),
          false,
      },
      &MonoPort::kDescriptorMethods,
      &descriptor_table_mono_5fport_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull MonoPort_class_data_ =
        MonoPort::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL MonoPort::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&MonoPort_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MonoPort_class_data_.tc_table);
  return MonoPort_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 30, 2>
MonoPort::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MonoPort, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    MonoPort_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::pmx::grpc::MonoPort>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string left = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(MonoPort, _impl_.left_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string left = 1;
    {PROTOBUF_FIELD_OFFSET(MonoPort, _impl_.left_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\4\0\0\0\0\0\0"
    "pmx.grpc.MonoPort"
    "left"
  }},
};
PROTOBUF_NOINLINE void MonoPort::Clear() {
// @@protoc_insertion_point(message_clear_start:pmx.grpc.MonoPort)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.left_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL MonoPort::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const MonoPort& this_ = static_cast<const MonoPort&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL MonoPort::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const MonoPort& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:pmx.grpc.MonoPort)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string left = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_left().empty()) {
      const std::string& _s = this_._internal_left();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "pmx.grpc.MonoPort.left");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pmx.grpc.MonoPort)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t MonoPort::ByteSizeLong(const MessageLite& base) {
  const MonoPort& this_ = static_cast<const MonoPort&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t MonoPort::ByteSizeLong() const {
  const MonoPort& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:pmx.grpc.MonoPort)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string left = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_left().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_left());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void MonoPort::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MonoPort*>(&to_msg);
  auto& from = static_cast<const MonoPort&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pmx.grpc.MonoPort)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_left().empty()) {
      _this->_internal_set_left(from._internal_left());
    } else {
      if (_this->_impl_.left_.IsDefault()) {
        _this->_internal_set_left("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MonoPort::CopyFrom(const MonoPort& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pmx.grpc.MonoPort)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MonoPort::InternalSwap(MonoPort* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.left_, &other->_impl_.left_, arena);
}

::google::protobuf::Metadata MonoPort::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace grpc
}  // namespace pmx
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_mono_5fport_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
