// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: output_ports.proto
// Protobuf C++ Version: 6.30.2

#include "output_ports.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace pmx {
namespace grpc {

inline constexpr SetOutputPortsRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : ports_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SetOutputPortsRequest::SetOutputPortsRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SetOutputPortsRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SetOutputPortsRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SetOutputPortsRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SetOutputPortsRequestDefaultTypeInternal() {}
  union {
    SetOutputPortsRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SetOutputPortsRequestDefaultTypeInternal _SetOutputPortsRequest_default_instance_;
}  // namespace grpc
}  // namespace pmx
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_output_5fports_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_output_5fports_2eproto = nullptr;
const ::uint32_t
    TableStruct_output_5fports_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::pmx::grpc::SetOutputPortsRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::pmx::grpc::SetOutputPortsRequest, _impl_.ports_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::pmx::grpc::SetOutputPortsRequest)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::pmx::grpc::_SetOutputPortsRequest_default_instance_._instance,
};
const char descriptor_table_protodef_output_5fports_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022output_ports.proto\022\010pmx.grpc\032\021stereo_p"
    "ort.proto\"<\n\025SetOutputPortsRequest\022#\n\005po"
    "rts\030\001 \003(\0132\024.pmx.grpc.StereoPortb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_output_5fports_2eproto_deps[1] = {
        &::descriptor_table_stereo_5fport_2eproto,
};
static ::absl::once_flag descriptor_table_output_5fports_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_output_5fports_2eproto = {
    false,
    false,
    119,
    descriptor_table_protodef_output_5fports_2eproto,
    "output_ports.proto",
    &descriptor_table_output_5fports_2eproto_once,
    descriptor_table_output_5fports_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_output_5fports_2eproto::offsets,
    file_level_enum_descriptors_output_5fports_2eproto,
    file_level_service_descriptors_output_5fports_2eproto,
};
namespace pmx {
namespace grpc {
// ===================================================================

class SetOutputPortsRequest::_Internal {
 public:
};

void SetOutputPortsRequest::clear_ports() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ports_.Clear();
}
SetOutputPortsRequest::SetOutputPortsRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SetOutputPortsRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:pmx.grpc.SetOutputPortsRequest)
}
PROTOBUF_NDEBUG_INLINE SetOutputPortsRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::pmx::grpc::SetOutputPortsRequest& from_msg)
      : ports_{visibility, arena, from.ports_},
        _cached_size_{0} {}

SetOutputPortsRequest::SetOutputPortsRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SetOutputPortsRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SetOutputPortsRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SetOutputPortsRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:pmx.grpc.SetOutputPortsRequest)
}
PROTOBUF_NDEBUG_INLINE SetOutputPortsRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : ports_{visibility, arena},
        _cached_size_{0} {}

inline void SetOutputPortsRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SetOutputPortsRequest::~SetOutputPortsRequest() {
  // @@protoc_insertion_point(destructor:pmx.grpc.SetOutputPortsRequest)
  SharedDtor(*this);
}
inline void SetOutputPortsRequest::SharedDtor(MessageLite& self) {
  SetOutputPortsRequest& this_ = static_cast<SetOutputPortsRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SetOutputPortsRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SetOutputPortsRequest(arena);
}
constexpr auto SetOutputPortsRequest::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(SetOutputPortsRequest, _impl_.ports_) +
          decltype(SetOutputPortsRequest::_impl_.ports_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(SetOutputPortsRequest), alignof(SetOutputPortsRequest), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&SetOutputPortsRequest::PlacementNew_,
                                 sizeof(SetOutputPortsRequest),
                                 alignof(SetOutputPortsRequest));
  }
}
constexpr auto SetOutputPortsRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SetOutputPortsRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SetOutputPortsRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SetOutputPortsRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SetOutputPortsRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SetOutputPortsRequest>(), &SetOutputPortsRequest::ByteSizeLong,
              &SetOutputPortsRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SetOutputPortsRequest, _impl_._cached_size_),
          false,
      },
      &SetOutputPortsRequest::kDescriptorMethods,
      &descriptor_table_output_5fports_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SetOutputPortsRequest_class_data_ =
        SetOutputPortsRequest::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL SetOutputPortsRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SetOutputPortsRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SetOutputPortsRequest_class_data_.tc_table);
  return SetOutputPortsRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
SetOutputPortsRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    SetOutputPortsRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::pmx::grpc::SetOutputPortsRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .pmx.grpc.StereoPort ports = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SetOutputPortsRequest, _impl_.ports_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .pmx.grpc.StereoPort ports = 1;
    {PROTOBUF_FIELD_OFFSET(SetOutputPortsRequest, _impl_.ports_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::pmx::grpc::StereoPort>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void SetOutputPortsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:pmx.grpc.SetOutputPortsRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ports_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SetOutputPortsRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SetOutputPortsRequest& this_ = static_cast<const SetOutputPortsRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SetOutputPortsRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SetOutputPortsRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:pmx.grpc.SetOutputPortsRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .pmx.grpc.StereoPort ports = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_ports_size());
       i < n; i++) {
    const auto& repfield = this_._internal_ports().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pmx.grpc.SetOutputPortsRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SetOutputPortsRequest::ByteSizeLong(const MessageLite& base) {
  const SetOutputPortsRequest& this_ = static_cast<const SetOutputPortsRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SetOutputPortsRequest::ByteSizeLong() const {
  const SetOutputPortsRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:pmx.grpc.SetOutputPortsRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .pmx.grpc.StereoPort ports = 1;
    {
      total_size += 1UL * this_._internal_ports_size();
      for (const auto& msg : this_._internal_ports()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SetOutputPortsRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SetOutputPortsRequest*>(&to_msg);
  auto& from = static_cast<const SetOutputPortsRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pmx.grpc.SetOutputPortsRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_ports()->MergeFrom(
      from._internal_ports());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SetOutputPortsRequest::CopyFrom(const SetOutputPortsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pmx.grpc.SetOutputPortsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SetOutputPortsRequest::InternalSwap(SetOutputPortsRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.ports_.InternalSwap(&other->_impl_.ports_);
}

::google::protobuf::Metadata SetOutputPortsRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace grpc
}  // namespace pmx
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_output_5fports_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
