// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: output_ports.proto
// Protobuf C++ Version: 6.31.1

#ifndef output_5fports_2eproto_2epb_2eh
#define output_5fports_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "stereo_port.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_output_5fports_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_output_5fports_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_output_5fports_2eproto;
}  // extern "C"
namespace pmx {
namespace grpc {
class SetOutputPortsRequest;
struct SetOutputPortsRequestDefaultTypeInternal;
extern SetOutputPortsRequestDefaultTypeInternal _SetOutputPortsRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SetOutputPortsRequest_class_data_;
}  // namespace grpc
}  // namespace pmx
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace pmx {
namespace grpc {

// ===================================================================


// -------------------------------------------------------------------

class SetOutputPortsRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:pmx.grpc.SetOutputPortsRequest) */ {
 public:
  inline SetOutputPortsRequest() : SetOutputPortsRequest(nullptr) {}
  ~SetOutputPortsRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SetOutputPortsRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SetOutputPortsRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SetOutputPortsRequest(::google::protobuf::internal::ConstantInitialized);

  inline SetOutputPortsRequest(const SetOutputPortsRequest& from) : SetOutputPortsRequest(nullptr, from) {}
  inline SetOutputPortsRequest(SetOutputPortsRequest&& from) noexcept
      : SetOutputPortsRequest(nullptr, ::std::move(from)) {}
  inline SetOutputPortsRequest& operator=(const SetOutputPortsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SetOutputPortsRequest& operator=(SetOutputPortsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SetOutputPortsRequest& default_instance() {
    return *reinterpret_cast<const SetOutputPortsRequest*>(
        &_SetOutputPortsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SetOutputPortsRequest& a, SetOutputPortsRequest& b) { a.Swap(&b); }
  inline void Swap(SetOutputPortsRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SetOutputPortsRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SetOutputPortsRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SetOutputPortsRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SetOutputPortsRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SetOutputPortsRequest& from) { SetOutputPortsRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SetOutputPortsRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "pmx.grpc.SetOutputPortsRequest"; }

 protected:
  explicit SetOutputPortsRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SetOutputPortsRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SetOutputPortsRequest& from);
  SetOutputPortsRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SetOutputPortsRequest&& from) noexcept
      : SetOutputPortsRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPortsFieldNumber = 1,
  };
  // repeated .pmx.grpc.StereoPort ports = 1;
  int ports_size() const;
  private:
  int _internal_ports_size() const;

  public:
  void clear_ports() ;
  ::pmx::grpc::StereoPort* PROTOBUF_NONNULL mutable_ports(int index);
  ::google::protobuf::RepeatedPtrField<::pmx::grpc::StereoPort>* PROTOBUF_NONNULL mutable_ports();

  private:
  const ::google::protobuf::RepeatedPtrField<::pmx::grpc::StereoPort>& _internal_ports() const;
  ::google::protobuf::RepeatedPtrField<::pmx::grpc::StereoPort>* PROTOBUF_NONNULL _internal_mutable_ports();
  public:
  const ::pmx::grpc::StereoPort& ports(int index) const;
  ::pmx::grpc::StereoPort* PROTOBUF_NONNULL add_ports();
  const ::google::protobuf::RepeatedPtrField<::pmx::grpc::StereoPort>& ports() const;
  // @@protoc_insertion_point(class_scope:pmx.grpc.SetOutputPortsRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SetOutputPortsRequest& from_msg);
    ::google::protobuf::RepeatedPtrField< ::pmx::grpc::StereoPort > ports_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_output_5fports_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SetOutputPortsRequest_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SetOutputPortsRequest

// repeated .pmx.grpc.StereoPort ports = 1;
inline int SetOutputPortsRequest::_internal_ports_size() const {
  return _internal_ports().size();
}
inline int SetOutputPortsRequest::ports_size() const {
  return _internal_ports_size();
}
inline ::pmx::grpc::StereoPort* PROTOBUF_NONNULL SetOutputPortsRequest::mutable_ports(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:pmx.grpc.SetOutputPortsRequest.ports)
  return _internal_mutable_ports()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::pmx::grpc::StereoPort>* PROTOBUF_NONNULL SetOutputPortsRequest::mutable_ports()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:pmx.grpc.SetOutputPortsRequest.ports)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_ports();
}
inline const ::pmx::grpc::StereoPort& SetOutputPortsRequest::ports(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:pmx.grpc.SetOutputPortsRequest.ports)
  return _internal_ports().Get(index);
}
inline ::pmx::grpc::StereoPort* PROTOBUF_NONNULL SetOutputPortsRequest::add_ports()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::pmx::grpc::StereoPort* _add = _internal_mutable_ports()->Add();
  // @@protoc_insertion_point(field_add:pmx.grpc.SetOutputPortsRequest.ports)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::pmx::grpc::StereoPort>& SetOutputPortsRequest::ports() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:pmx.grpc.SetOutputPortsRequest.ports)
  return _internal_ports();
}
inline const ::google::protobuf::RepeatedPtrField<::pmx::grpc::StereoPort>&
SetOutputPortsRequest::_internal_ports() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ports_;
}
inline ::google::protobuf::RepeatedPtrField<::pmx::grpc::StereoPort>* PROTOBUF_NONNULL
SetOutputPortsRequest::_internal_mutable_ports() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.ports_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace grpc
}  // namespace pmx


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // output_5fports_2eproto_2epb_2eh
