// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pmx_grpc.proto
// Protobuf C++ Version: 5.29.2

#include "pmx_grpc.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace pmx {
namespace grpc {
}  // namespace grpc
}  // namespace pmx
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_pmx_5fgrpc_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_pmx_5fgrpc_2eproto = nullptr;
const ::uint32_t TableStruct_pmx_5fgrpc_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_pmx_5fgrpc_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016pmx_grpc.proto\022\010pmx.grpc\032\nport.proto\032\022"
    "output_ports.proto\032\021input_ports.proto\032\016r"
    "esponse.proto2\335\001\n\007PmxGrpc\022D\n\tListPorts\022\032"
    ".pmx.grpc.ListPortsRequest\032\033.pmx.grpc.Li"
    "stPortsResponse\022E\n\016SetOutputPorts\022\037.pmx."
    "grpc.SetOutputPortsRequest\032\022.pmx.grpc.Re"
    "sponse\022E\n\016SetupInputPort\022\037.pmx.grpc.Setu"
    "pInputPortRequest\032\022.pmx.grpc.Responseb\006p"
    "roto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_pmx_5fgrpc_2eproto_deps[4] =
    {
        &::descriptor_table_input_5fports_2eproto,
        &::descriptor_table_output_5fports_2eproto,
        &::descriptor_table_port_2eproto,
        &::descriptor_table_response_2eproto,
};
static ::absl::once_flag descriptor_table_pmx_5fgrpc_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_pmx_5fgrpc_2eproto = {
    false,
    false,
    325,
    descriptor_table_protodef_pmx_5fgrpc_2eproto,
    "pmx_grpc.proto",
    &descriptor_table_pmx_5fgrpc_2eproto_once,
    descriptor_table_pmx_5fgrpc_2eproto_deps,
    4,
    0,
    schemas,
    file_default_instances,
    TableStruct_pmx_5fgrpc_2eproto::offsets,
    file_level_enum_descriptors_pmx_5fgrpc_2eproto,
    file_level_service_descriptors_pmx_5fgrpc_2eproto,
};
namespace pmx {
namespace grpc {
// @@protoc_insertion_point(namespace_scope)
}  // namespace grpc
}  // namespace pmx
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_pmx_5fgrpc_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
