// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: port.proto
// Protobuf C++ Version: 6.30.2

#ifndef port_2eproto_2epb_2eh
#define port_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_port_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_port_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_port_2eproto;
}  // extern "C"
namespace pmx {
namespace grpc {
enum PortDirection : int;
extern const uint32_t PortDirection_internal_data_[];
class ListPort;
struct ListPortDefaultTypeInternal;
extern ListPortDefaultTypeInternal _ListPort_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ListPort_class_data_;
class ListPortsRequest;
struct ListPortsRequestDefaultTypeInternal;
extern ListPortsRequestDefaultTypeInternal _ListPortsRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ListPortsRequest_class_data_;
class ListPortsResponse;
struct ListPortsResponseDefaultTypeInternal;
extern ListPortsResponseDefaultTypeInternal _ListPortsResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ListPortsResponse_class_data_;
}  // namespace grpc
}  // namespace pmx
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::pmx::grpc::PortDirection_internal_data_>
    internal::EnumTraitsImpl::value<::pmx::grpc::PortDirection>;
}  // namespace protobuf
}  // namespace google

namespace pmx {
namespace grpc {
enum PortDirection : int {
  IN = 0,
  OUT = 1,
  UNKNOWN = 2,
  PortDirection_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  PortDirection_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t PortDirection_internal_data_[];
inline constexpr PortDirection PortDirection_MIN =
    static_cast<PortDirection>(0);
inline constexpr PortDirection PortDirection_MAX =
    static_cast<PortDirection>(2);
inline bool PortDirection_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int PortDirection_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PortDirection_descriptor();
template <typename T>
const std::string& PortDirection_Name(T value) {
  static_assert(std::is_same<T, PortDirection>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to PortDirection_Name().");
  return PortDirection_Name(static_cast<PortDirection>(value));
}
template <>
inline const std::string& PortDirection_Name(PortDirection value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PortDirection_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool PortDirection_Parse(
    absl::string_view name, PortDirection* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<PortDirection>(PortDirection_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class ListPortsRequest final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:pmx.grpc.ListPortsRequest) */ {
 public:
  inline ListPortsRequest() : ListPortsRequest(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ListPortsRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ListPortsRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ListPortsRequest(::google::protobuf::internal::ConstantInitialized);

  inline ListPortsRequest(const ListPortsRequest& from) : ListPortsRequest(nullptr, from) {}
  inline ListPortsRequest(ListPortsRequest&& from) noexcept
      : ListPortsRequest(nullptr, std::move(from)) {}
  inline ListPortsRequest& operator=(const ListPortsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ListPortsRequest& operator=(ListPortsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ListPortsRequest& default_instance() {
    return *reinterpret_cast<const ListPortsRequest*>(
        &_ListPortsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ListPortsRequest& a, ListPortsRequest& b) { a.Swap(&b); }
  inline void Swap(ListPortsRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ListPortsRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ListPortsRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<ListPortsRequest>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const ListPortsRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const ListPortsRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "pmx.grpc.ListPortsRequest"; }

 protected:
  explicit ListPortsRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ListPortsRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ListPortsRequest& from);
  ListPortsRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ListPortsRequest&& from) noexcept
      : ListPortsRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:pmx.grpc.ListPortsRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ListPortsRequest& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_port_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ListPortsRequest_class_data_;
// -------------------------------------------------------------------

class ListPort final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:pmx.grpc.ListPort) */ {
 public:
  inline ListPort() : ListPort(nullptr) {}
  ~ListPort() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ListPort* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ListPort));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ListPort(::google::protobuf::internal::ConstantInitialized);

  inline ListPort(const ListPort& from) : ListPort(nullptr, from) {}
  inline ListPort(ListPort&& from) noexcept
      : ListPort(nullptr, std::move(from)) {}
  inline ListPort& operator=(const ListPort& from) {
    CopyFrom(from);
    return *this;
  }
  inline ListPort& operator=(ListPort&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ListPort& default_instance() {
    return *reinterpret_cast<const ListPort*>(
        &_ListPort_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ListPort& a, ListPort& b) { a.Swap(&b); }
  inline void Swap(ListPort* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ListPort* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ListPort* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ListPort>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ListPort& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ListPort& from) { ListPort::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ListPort* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "pmx.grpc.ListPort"; }

 protected:
  explicit ListPort(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ListPort(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ListPort& from);
  ListPort(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ListPort&& from) noexcept
      : ListPort(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 1,
    kAliasFieldNumber = 6,
    kGroupFieldNumber = 7,
    kPathFieldNumber = 8,
    kDspFormatFieldNumber = 9,
    kAudioChannelFieldNumber = 10,
    kIdFieldNumber = 2,
    kNodeIdFieldNumber = 3,
    kDirectionFieldNumber = 4,
    kPhysicalFieldNumber = 5,
    kIsMonitorFieldNumber = 12,
    kObjectSerialFieldNumber = 11,
  };
  // string name = 1;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // string alias = 6;
  void clear_alias() ;
  const std::string& alias() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_alias(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_alias();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_alias();
  void set_allocated_alias(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_alias() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_alias(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_alias();

  public:
  // string group = 7;
  void clear_group() ;
  const std::string& group() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_group(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_group();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_group();
  void set_allocated_group(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_group() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_group(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_group();

  public:
  // string path = 8;
  void clear_path() ;
  const std::string& path() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_path(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_path();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_path();
  void set_allocated_path(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_path() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_path(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_path();

  public:
  // string dsp_format = 9;
  void clear_dsp_format() ;
  const std::string& dsp_format() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_dsp_format(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_dsp_format();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_dsp_format();
  void set_allocated_dsp_format(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_dsp_format() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_dsp_format(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_dsp_format();

  public:
  // string audio_channel = 10;
  void clear_audio_channel() ;
  const std::string& audio_channel() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_audio_channel(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_audio_channel();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_audio_channel();
  void set_allocated_audio_channel(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_audio_channel() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_audio_channel(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_audio_channel();

  public:
  // uint32 id = 2;
  void clear_id() ;
  ::uint32_t id() const;
  void set_id(::uint32_t value);

  private:
  ::uint32_t _internal_id() const;
  void _internal_set_id(::uint32_t value);

  public:
  // uint32 node_id = 3;
  void clear_node_id() ;
  ::uint32_t node_id() const;
  void set_node_id(::uint32_t value);

  private:
  ::uint32_t _internal_node_id() const;
  void _internal_set_node_id(::uint32_t value);

  public:
  // .pmx.grpc.PortDirection direction = 4;
  void clear_direction() ;
  ::pmx::grpc::PortDirection direction() const;
  void set_direction(::pmx::grpc::PortDirection value);

  private:
  ::pmx::grpc::PortDirection _internal_direction() const;
  void _internal_set_direction(::pmx::grpc::PortDirection value);

  public:
  // bool physical = 5;
  void clear_physical() ;
  bool physical() const;
  void set_physical(bool value);

  private:
  bool _internal_physical() const;
  void _internal_set_physical(bool value);

  public:
  // bool is_monitor = 12;
  void clear_is_monitor() ;
  bool is_monitor() const;
  void set_is_monitor(bool value);

  private:
  bool _internal_is_monitor() const;
  void _internal_set_is_monitor(bool value);

  public:
  // uint32 object_serial = 11;
  void clear_object_serial() ;
  ::uint32_t object_serial() const;
  void set_object_serial(::uint32_t value);

  private:
  ::uint32_t _internal_object_serial() const;
  void _internal_set_object_serial(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:pmx.grpc.ListPort)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 12,
                                   0, 75,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ListPort& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::internal::ArenaStringPtr alias_;
    ::google::protobuf::internal::ArenaStringPtr group_;
    ::google::protobuf::internal::ArenaStringPtr path_;
    ::google::protobuf::internal::ArenaStringPtr dsp_format_;
    ::google::protobuf::internal::ArenaStringPtr audio_channel_;
    ::uint32_t id_;
    ::uint32_t node_id_;
    int direction_;
    bool physical_;
    bool is_monitor_;
    ::uint32_t object_serial_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_port_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ListPort_class_data_;
// -------------------------------------------------------------------

class ListPortsResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:pmx.grpc.ListPortsResponse) */ {
 public:
  inline ListPortsResponse() : ListPortsResponse(nullptr) {}
  ~ListPortsResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ListPortsResponse* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ListPortsResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ListPortsResponse(::google::protobuf::internal::ConstantInitialized);

  inline ListPortsResponse(const ListPortsResponse& from) : ListPortsResponse(nullptr, from) {}
  inline ListPortsResponse(ListPortsResponse&& from) noexcept
      : ListPortsResponse(nullptr, std::move(from)) {}
  inline ListPortsResponse& operator=(const ListPortsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ListPortsResponse& operator=(ListPortsResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ListPortsResponse& default_instance() {
    return *reinterpret_cast<const ListPortsResponse*>(
        &_ListPortsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ListPortsResponse& a, ListPortsResponse& b) { a.Swap(&b); }
  inline void Swap(ListPortsResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ListPortsResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ListPortsResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ListPortsResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ListPortsResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ListPortsResponse& from) { ListPortsResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ListPortsResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "pmx.grpc.ListPortsResponse"; }

 protected:
  explicit ListPortsResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ListPortsResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ListPortsResponse& from);
  ListPortsResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ListPortsResponse&& from) noexcept
      : ListPortsResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPortsFieldNumber = 1,
  };
  // repeated .pmx.grpc.ListPort ports = 1;
  int ports_size() const;
  private:
  int _internal_ports_size() const;

  public:
  void clear_ports() ;
  ::pmx::grpc::ListPort* PROTOBUF_NONNULL mutable_ports(int index);
  ::google::protobuf::RepeatedPtrField<::pmx::grpc::ListPort>* PROTOBUF_NONNULL mutable_ports();

  private:
  const ::google::protobuf::RepeatedPtrField<::pmx::grpc::ListPort>& _internal_ports() const;
  ::google::protobuf::RepeatedPtrField<::pmx::grpc::ListPort>* PROTOBUF_NONNULL _internal_mutable_ports();
  public:
  const ::pmx::grpc::ListPort& ports(int index) const;
  ::pmx::grpc::ListPort* PROTOBUF_NONNULL add_ports();
  const ::google::protobuf::RepeatedPtrField<::pmx::grpc::ListPort>& ports() const;
  // @@protoc_insertion_point(class_scope:pmx.grpc.ListPortsResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ListPortsResponse& from_msg);
    ::google::protobuf::RepeatedPtrField< ::pmx::grpc::ListPort > ports_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_port_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ListPortsResponse_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ListPort

// uint32 id = 2;
inline void ListPort::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline ::uint32_t ListPort::id() const {
  // @@protoc_insertion_point(field_get:pmx.grpc.ListPort.id)
  return _internal_id();
}
inline void ListPort::set_id(::uint32_t value) {
  _internal_set_id(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:pmx.grpc.ListPort.id)
}
inline ::uint32_t ListPort::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void ListPort::_internal_set_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// uint32 node_id = 3;
inline void ListPort::clear_node_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.node_id_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline ::uint32_t ListPort::node_id() const {
  // @@protoc_insertion_point(field_get:pmx.grpc.ListPort.node_id)
  return _internal_node_id();
}
inline void ListPort::set_node_id(::uint32_t value) {
  _internal_set_node_id(value);
  _impl_._has_bits_[0] |= 0x00000080u;
  // @@protoc_insertion_point(field_set:pmx.grpc.ListPort.node_id)
}
inline ::uint32_t ListPort::_internal_node_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.node_id_;
}
inline void ListPort::_internal_set_node_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.node_id_ = value;
}

// uint32 object_serial = 11;
inline void ListPort::clear_object_serial() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.object_serial_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000800u;
}
inline ::uint32_t ListPort::object_serial() const {
  // @@protoc_insertion_point(field_get:pmx.grpc.ListPort.object_serial)
  return _internal_object_serial();
}
inline void ListPort::set_object_serial(::uint32_t value) {
  _internal_set_object_serial(value);
  _impl_._has_bits_[0] |= 0x00000800u;
  // @@protoc_insertion_point(field_set:pmx.grpc.ListPort.object_serial)
}
inline ::uint32_t ListPort::_internal_object_serial() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.object_serial_;
}
inline void ListPort::_internal_set_object_serial(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.object_serial_ = value;
}

// string name = 1;
inline void ListPort::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ListPort::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:pmx.grpc.ListPort.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ListPort::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:pmx.grpc.ListPort.name)
}
inline std::string* PROTOBUF_NONNULL ListPort::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:pmx.grpc.ListPort.name)
  return _s;
}
inline const std::string& ListPort::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void ListPort::_internal_set_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL ListPort::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE ListPort::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:pmx.grpc.ListPort.name)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void ListPort::set_allocated_name(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:pmx.grpc.ListPort.name)
}

// .pmx.grpc.PortDirection direction = 4;
inline void ListPort::clear_direction() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.direction_ = 0;
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline ::pmx::grpc::PortDirection ListPort::direction() const {
  // @@protoc_insertion_point(field_get:pmx.grpc.ListPort.direction)
  return _internal_direction();
}
inline void ListPort::set_direction(::pmx::grpc::PortDirection value) {
  _internal_set_direction(value);
  _impl_._has_bits_[0] |= 0x00000100u;
  // @@protoc_insertion_point(field_set:pmx.grpc.ListPort.direction)
}
inline ::pmx::grpc::PortDirection ListPort::_internal_direction() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::pmx::grpc::PortDirection>(_impl_.direction_);
}
inline void ListPort::_internal_set_direction(::pmx::grpc::PortDirection value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.direction_ = value;
}

// bool physical = 5;
inline void ListPort::clear_physical() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.physical_ = false;
  _impl_._has_bits_[0] &= ~0x00000200u;
}
inline bool ListPort::physical() const {
  // @@protoc_insertion_point(field_get:pmx.grpc.ListPort.physical)
  return _internal_physical();
}
inline void ListPort::set_physical(bool value) {
  _internal_set_physical(value);
  _impl_._has_bits_[0] |= 0x00000200u;
  // @@protoc_insertion_point(field_set:pmx.grpc.ListPort.physical)
}
inline bool ListPort::_internal_physical() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.physical_;
}
inline void ListPort::_internal_set_physical(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.physical_ = value;
}

// string alias = 6;
inline void ListPort::clear_alias() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.alias_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& ListPort::alias() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:pmx.grpc.ListPort.alias)
  return _internal_alias();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ListPort::set_alias(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.alias_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:pmx.grpc.ListPort.alias)
}
inline std::string* PROTOBUF_NONNULL ListPort::mutable_alias()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_alias();
  // @@protoc_insertion_point(field_mutable:pmx.grpc.ListPort.alias)
  return _s;
}
inline const std::string& ListPort::_internal_alias() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.alias_.Get();
}
inline void ListPort::_internal_set_alias(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.alias_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL ListPort::_internal_mutable_alias() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.alias_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE ListPort::release_alias() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:pmx.grpc.ListPort.alias)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.alias_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.alias_.Set("", GetArena());
  }
  return released;
}
inline void ListPort::set_allocated_alias(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.alias_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.alias_.IsDefault()) {
    _impl_.alias_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:pmx.grpc.ListPort.alias)
}

// string group = 7;
inline void ListPort::clear_group() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.group_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& ListPort::group() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:pmx.grpc.ListPort.group)
  return _internal_group();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ListPort::set_group(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.group_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:pmx.grpc.ListPort.group)
}
inline std::string* PROTOBUF_NONNULL ListPort::mutable_group()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_group();
  // @@protoc_insertion_point(field_mutable:pmx.grpc.ListPort.group)
  return _s;
}
inline const std::string& ListPort::_internal_group() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.group_.Get();
}
inline void ListPort::_internal_set_group(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.group_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL ListPort::_internal_mutable_group() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.group_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE ListPort::release_group() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:pmx.grpc.ListPort.group)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.group_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.group_.Set("", GetArena());
  }
  return released;
}
inline void ListPort::set_allocated_group(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.group_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.group_.IsDefault()) {
    _impl_.group_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:pmx.grpc.ListPort.group)
}

// string path = 8;
inline void ListPort::clear_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.path_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& ListPort::path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:pmx.grpc.ListPort.path)
  return _internal_path();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ListPort::set_path(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.path_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:pmx.grpc.ListPort.path)
}
inline std::string* PROTOBUF_NONNULL ListPort::mutable_path()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_path();
  // @@protoc_insertion_point(field_mutable:pmx.grpc.ListPort.path)
  return _s;
}
inline const std::string& ListPort::_internal_path() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.path_.Get();
}
inline void ListPort::_internal_set_path(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.path_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL ListPort::_internal_mutable_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.path_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE ListPort::release_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:pmx.grpc.ListPort.path)
  if ((_impl_._has_bits_[0] & 0x00000008u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* released = _impl_.path_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.path_.Set("", GetArena());
  }
  return released;
}
inline void ListPort::set_allocated_path(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.path_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.path_.IsDefault()) {
    _impl_.path_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:pmx.grpc.ListPort.path)
}

// string dsp_format = 9;
inline void ListPort::clear_dsp_format() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dsp_format_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline const std::string& ListPort::dsp_format() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:pmx.grpc.ListPort.dsp_format)
  return _internal_dsp_format();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ListPort::set_dsp_format(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.dsp_format_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:pmx.grpc.ListPort.dsp_format)
}
inline std::string* PROTOBUF_NONNULL ListPort::mutable_dsp_format()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_dsp_format();
  // @@protoc_insertion_point(field_mutable:pmx.grpc.ListPort.dsp_format)
  return _s;
}
inline const std::string& ListPort::_internal_dsp_format() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dsp_format_.Get();
}
inline void ListPort::_internal_set_dsp_format(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.dsp_format_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL ListPort::_internal_mutable_dsp_format() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000010u;
  return _impl_.dsp_format_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE ListPort::release_dsp_format() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:pmx.grpc.ListPort.dsp_format)
  if ((_impl_._has_bits_[0] & 0x00000010u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000010u;
  auto* released = _impl_.dsp_format_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.dsp_format_.Set("", GetArena());
  }
  return released;
}
inline void ListPort::set_allocated_dsp_format(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  _impl_.dsp_format_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.dsp_format_.IsDefault()) {
    _impl_.dsp_format_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:pmx.grpc.ListPort.dsp_format)
}

// string audio_channel = 10;
inline void ListPort::clear_audio_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.audio_channel_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline const std::string& ListPort::audio_channel() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:pmx.grpc.ListPort.audio_channel)
  return _internal_audio_channel();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ListPort::set_audio_channel(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.audio_channel_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:pmx.grpc.ListPort.audio_channel)
}
inline std::string* PROTOBUF_NONNULL ListPort::mutable_audio_channel()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_audio_channel();
  // @@protoc_insertion_point(field_mutable:pmx.grpc.ListPort.audio_channel)
  return _s;
}
inline const std::string& ListPort::_internal_audio_channel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.audio_channel_.Get();
}
inline void ListPort::_internal_set_audio_channel(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.audio_channel_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL ListPort::_internal_mutable_audio_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000020u;
  return _impl_.audio_channel_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE ListPort::release_audio_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:pmx.grpc.ListPort.audio_channel)
  if ((_impl_._has_bits_[0] & 0x00000020u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000020u;
  auto* released = _impl_.audio_channel_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.audio_channel_.Set("", GetArena());
  }
  return released;
}
inline void ListPort::set_allocated_audio_channel(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000020u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020u;
  }
  _impl_.audio_channel_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.audio_channel_.IsDefault()) {
    _impl_.audio_channel_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:pmx.grpc.ListPort.audio_channel)
}

// bool is_monitor = 12;
inline void ListPort::clear_is_monitor() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_monitor_ = false;
  _impl_._has_bits_[0] &= ~0x00000400u;
}
inline bool ListPort::is_monitor() const {
  // @@protoc_insertion_point(field_get:pmx.grpc.ListPort.is_monitor)
  return _internal_is_monitor();
}
inline void ListPort::set_is_monitor(bool value) {
  _internal_set_is_monitor(value);
  _impl_._has_bits_[0] |= 0x00000400u;
  // @@protoc_insertion_point(field_set:pmx.grpc.ListPort.is_monitor)
}
inline bool ListPort::_internal_is_monitor() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_monitor_;
}
inline void ListPort::_internal_set_is_monitor(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_monitor_ = value;
}

// -------------------------------------------------------------------

// ListPortsRequest

// -------------------------------------------------------------------

// ListPortsResponse

// repeated .pmx.grpc.ListPort ports = 1;
inline int ListPortsResponse::_internal_ports_size() const {
  return _internal_ports().size();
}
inline int ListPortsResponse::ports_size() const {
  return _internal_ports_size();
}
inline void ListPortsResponse::clear_ports() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ports_.Clear();
}
inline ::pmx::grpc::ListPort* PROTOBUF_NONNULL ListPortsResponse::mutable_ports(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:pmx.grpc.ListPortsResponse.ports)
  return _internal_mutable_ports()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::pmx::grpc::ListPort>* PROTOBUF_NONNULL ListPortsResponse::mutable_ports()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:pmx.grpc.ListPortsResponse.ports)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_ports();
}
inline const ::pmx::grpc::ListPort& ListPortsResponse::ports(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:pmx.grpc.ListPortsResponse.ports)
  return _internal_ports().Get(index);
}
inline ::pmx::grpc::ListPort* PROTOBUF_NONNULL ListPortsResponse::add_ports()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::pmx::grpc::ListPort* _add = _internal_mutable_ports()->Add();
  // @@protoc_insertion_point(field_add:pmx.grpc.ListPortsResponse.ports)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::pmx::grpc::ListPort>& ListPortsResponse::ports() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:pmx.grpc.ListPortsResponse.ports)
  return _internal_ports();
}
inline const ::google::protobuf::RepeatedPtrField<::pmx::grpc::ListPort>&
ListPortsResponse::_internal_ports() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ports_;
}
inline ::google::protobuf::RepeatedPtrField<::pmx::grpc::ListPort>* PROTOBUF_NONNULL
ListPortsResponse::_internal_mutable_ports() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.ports_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace grpc
}  // namespace pmx


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::pmx::grpc::PortDirection> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::pmx::grpc::PortDirection>() {
  return ::pmx::grpc::PortDirection_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // port_2eproto_2epb_2eh
